version: "3.7"

services:
  api:
    build:
      context: ./api_project/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "./api_project:/home/user/api_project"
    depends_on:
      - db
    command: ["run", "uwsgi", "--ini", "./uwsgi.ini"]
  pipenv:
    build:
      context: ./api_project/
      dockerfile: Dockerfile
    volumes:
      - "./api_project:/home/user/api_project"
  db:
    image: "postgres:latest"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "default"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "devpassword"
      POSTGRES_HOST: "0.0.0.0"
      PGDATA: /var/lib/postgresql/data/pg_data
    volumes:
      - "./api_project/database_data:/var/lib/postgresql/data"
