# Generated by Django 3.1.3 on 2020-11-09 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201107_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='soft_delete',
        ),
        migrations.RemoveField(
            model_name='card',
            name='soft_delete',
        ),
        migrations.RemoveField(
            model_name='cardlist',
            name='soft_delete',
        ),
        migrations.RemoveField(
            model_name='user',
            name='soft_delete',
        ),
    ]
